version: '3'
services:
  db:
    image: postgres:10
    ports: 
      - '4545:5432'
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<%= ENV["DATABASE_ADMIN_PASSWORD"] %>
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/futnews-api
    ports:
      - "5000:5000"
    depends_on:
      - db