version: '3'
services:
  db_prod:
    image: postgres:10
    ports: 
      - '4546:5432'
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<%= ENV["DATABASE_ADMIN_PASSWORD"] %>
    volumes:
      - /var/lib/postgresql/data
    restart: unless-stopped
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/futnews-api
    ports:
      - "5000:5000"
    depends_on:
      - db_prod
    restart: unless-stopped